-- Apply to an existing PostgreSQL database before deploying the Brevo integration.
-- Existing marketing consents stay unassigned: their organizer cannot be inferred safely.
ALTER TABLE marketing_subscriber ADD COLUMN IF NOT EXISTS owner_id bigint;
ALTER TABLE marketing_subscriber ADD COLUMN IF NOT EXISTS consent_event_id bigint;
ALTER TABLE marketing_subscriber ADD COLUMN IF NOT EXISTS consent_version varchar(40);
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_marketing_owner') THEN
        ALTER TABLE marketing_subscriber
            ADD CONSTRAINT fk_marketing_owner FOREIGN KEY (owner_id) REFERENCES users(id);
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uk_marketing_owner_email
    ON marketing_subscriber (owner_id, email_lookup_hash);

CREATE TABLE IF NOT EXISTS brevo_connection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id bigint NOT NULL UNIQUE REFERENCES users(id),
    api_key_ciphertext varchar(2048) NOT NULL,
    list_id bigint NOT NULL,
    organization_id varchar(100) NOT NULL,
    webhook_id bigint NOT NULL,
    webhook_secret_hash varchar(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS brevo_sync_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id bigint NOT NULL REFERENCES users(id),
    email_lookup_hash varchar(67) NOT NULL,
    email_ciphertext varchar(1024) NOT NULL,
    updated_at timestamp NOT NULL,
    revision bigint NOT NULL,
    CONSTRAINT uk_brevo_sync_owner_email UNIQUE (owner_id, email_lookup_hash)
);
CREATE INDEX IF NOT EXISTS ix_brevo_sync_updated_at ON brevo_sync_job (updated_at);
