-- Apply to an existing PostgreSQL database before deploying booking email retries.
CREATE TABLE IF NOT EXISTS booking_confirmation_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL UNIQUE REFERENCES booking(id) ON DELETE CASCADE,
    unsubscribe_token_ciphertext varchar(1024),
    attempts integer NOT NULL,
    next_attempt_at timestamp NOT NULL,
    created_at timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_booking_confirmation_next_attempt
    ON booking_confirmation_job (next_attempt_at);
