-- Run before deploying the organizer SMTP settings feature on an existing PostgreSQL database.
CREATE TABLE IF NOT EXISTS owner_smtp_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id bigint NOT NULL UNIQUE REFERENCES users(id),
    host varchar(253) NOT NULL,
    port integer NOT NULL,
    encryption varchar(16) NOT NULL,
    username varchar(320) NOT NULL,
    password_ciphertext varchar(2048) NOT NULL,
    from_email varchar(320) NOT NULL,
    from_name varchar(100) NOT NULL
);
